Syncing metadata links in redis
webaverse/redis-server pull request #6
Opened 2021-11-18 00:07 UTC by hamzatrq

Syncing the metadata uris in redis

2021-11-25 17:57 UTC, hamzatrq commented
This PR needs to be reviewed and merged for the latest PR for backend-api to work properly.

2021-11-26 02:11 UTC, avaer commented on getTokenIds-test.js
> +    fetchedURI = Object.values((await getRedisItem('2', redisPrefixes[config.contractName]+'uris')).Item).join('');
This is a big mess. I have no idea what this is supposed to be, or what these mysterious constants and coersions are.

Can this be separate lines?

2021-11-26 02:11 UTC, avaer commented on tokens.js
> +      if (isIPFS.url(tokenURI)) {
Definitely do not resolve the token on the Redis side.

2021-11-26 02:12 UTC, avaer commented on package.json
> +    "is-ipfs": "^6.0.2",
Remove this.

2021-11-26 02:12 UTC, avaer commented on cache.js
> +      await putRedisItem(`${uri.tokenId}`, `${uri.tokenURI}`, redisPrefixes[config.contractName] + 'uris');
What is the point of this weird stringification? Are the types so unclear that there is a coersion needed?

2021-11-26 02:13 UTC, avaer requested changes
Major code and design problems.

IPFS should have nothing to do with the redis server, and the code is a mess in the typing.

2021-11-28 05:50 UTC, closed without merging